### ISSUE TITLE
偶尔显示的是汉字

### ISSUE THREAD

**Issue by FlyingOnion** [uuware/icons-font-customization#1]
过一段时间才正常

**Comment by FlyingOnion** [comment]
![无标题](https://user-images.githubusercontent.com/17760761/101115536-80a2be00-361e-11eb-915e-a7f97e6b3da7.png)
![无标题1](https://user-images.githubusercontent.com/17760761/101115547-839dae80-361e-11eb-802f-1466787ccc7f.png)

**Comment by uuware** [comment]
这是因为展示页的字体文件包含所有字体，所以非常大，浏览器装载需要时间。在装载完成之前，浏览器用默认字体显示。实际使用时不会出现这种情况。
