### ISSUE TITLE
有些图标显示凌乱

### ISSUE THREAD

**Issue by liaoxuewei** [uuware/icons-font-customization#3]
![image](https://user-images.githubusercontent.com/970765/103071229-2a61e300-45fe-11eb-9550-381d734336af.png)
![image](https://user-images.githubusercontent.com/970765/103071445-917f9780-45fe-11eb-8988-b23633fb6177.png)
有些图标显示凌乱是什么情况？--注：我是本地打开的。

**Comment by liaoxuewei** [comment]
搜索font字符会得到第一张图

**Comment by uuware** [comment]
谢谢关注和测试。
这两个问题都不好解决，我已经列入已知问题，（暂且）也不打算解决了。
第一个问题是，有些商标不是正方形。例如你列出来的就是两个横长方形的图标。本程序为了方便排列和改变图标大小，都假设所有图标都是正方形，所以对于一些不正规的，就出现覆盖，看起来凌乱了。如果你单独下载图片，或单独使用它，也还是能用。这也是没有删剔除它的原因。
第二个问题更难。svg中当线有交叉形成内外区域后，是否填满或空白这个区域，有一个机制叫fill-rule="evenodd"/"nonzero"。而怎么正确识别判断它，还没找到一个Node.js能处理的有效办法。这个程序使用了svgo来处理svg，然后转换为字体。这个转换过程中或略了fill-rule而产生了这个问题。
https://github.com/svg/svgo/issues/1092
中有这个描述。
但是下载为图片的时候，因为使用了浏览器的功能，所以图片是正常的。
